// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvRC8fZe2OO6Y0llsHt3oITKSpzKp7TmQ',
    appId: '1:722550311716:web:2f60b5ea5bb60034ab41b1',
    messagingSenderId: '722550311716',
    projectId: 'database-gtr-101c5',
    authDomain: 'database-gtr-101c5.firebaseapp.com',
    storageBucket: 'database-gtr-101c5.firebasestorage.app',
    measurementId: 'G-VE7N2BDS3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZDRNxrWcfTmkBmbivC0HZELbDkjMSuqs',
    appId: '1:722550311716:android:8bd973d45d4ae7caab41b1',
    messagingSenderId: '722550311716',
    projectId: 'database-gtr-101c5',
    storageBucket: 'database-gtr-101c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjOPj3MUo3KxjX7gNBngsFrsSSlwVsgc',
    appId: '1:722550311716:ios:44ddcb3ee879d681ab41b1',
    messagingSenderId: '722550311716',
    projectId: 'database-gtr-101c5',
    storageBucket: 'database-gtr-101c5.firebasestorage.app',
    iosBundleId: 'com.example.mini008',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjOPj3MUo3KxjX7gNBngsFrsSSlwVsgc',
    appId: '1:722550311716:ios:44ddcb3ee879d681ab41b1',
    messagingSenderId: '722550311716',
    projectId: 'database-gtr-101c5',
    storageBucket: 'database-gtr-101c5.firebasestorage.app',
    iosBundleId: 'com.example.mini008',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvRC8fZe2OO6Y0llsHt3oITKSpzKp7TmQ',
    appId: '1:722550311716:web:1cbced00564134feab41b1',
    messagingSenderId: '722550311716',
    projectId: 'database-gtr-101c5',
    authDomain: 'database-gtr-101c5.firebaseapp.com',
    storageBucket: 'database-gtr-101c5.firebasestorage.app',
    measurementId: 'G-32CNBJERF2',
  );
}
